### ISSUE TITLE
UI Canvas

### ISSUE THREAD

**Issue by vleango** [prime31/TransitionKit#2]
My entire app is using only Canvas elements (buttons, texts, panels, etc).
The canvas is always on top of the scene resulting in the transition to not be displayed.
How to fix this?

**Comment by prime31** [comment]
Canvases are rendered last if dealing with screen space UI. You can just hide it during the transition then reshow it when the transition completes.

Mike

On Feb 26, 2015, at 12:32 AM, vleango notifications@github.com wrote:

My entire app is using only Canvas elements (buttons, texts, panels, etc).
The canvas is always on top of the scene resulting in the transition to not be displayed.
How to fix this?

**Comment by vleango** [comment]
Thanks for the feedback. I was using the canvas directly. I'll make it to a prefab and try your suggestion. Thanks a lot.

**Comment by Gasparfx** [comment]
@vleango You can also change Canvas Render Mode to "Screen Space - Camera".

**Comment by prime31** [comment]
Yes. Good point. That will allow the UI to act like any other object rendered in your scene.

Mike

On Mar 11, 2015, at 1:18 AM, Gasparfx notifications@github.com wrote:

@vleango You can also change Canvas Render Mode to "Screen Space - Camera".

**Comment by vleango** [comment]
Thank you for the feed back @Gasparfx @prime31! I will close this
