### ISSUE TITLE
Transition Kit Doesn't work on Android

### ISSUE THREAD

**Issue by cluckeyetea** [prime31/TransitionKit#3]
I really like the concept here and the transitions look slick on the Web Player and in the Unity editor. But on Android all my transitions are just big pink boxes. It's like the initial screen grab doesn't work or something. Maybe I'm doing something wrong? Is anybody using this project on Android?

**Comment by prime31** [comment]
TK works fine on any recent Android devices. Make sure you are following the steps to include the shaders in your build as detailed in the README

Mike

On Mar 22, 2015, at 6:06 PM, cluckeyetea notifications@github.com wrote:

I really like the concept here and the transitions look slick on the Web Player and in the Unity editor. But on Android all my transitions are just big pink boxes. It's like the initial screen grab doesn't work or something.

**Comment by cluckeyetea** [comment]
Thanks, Mike. Good to know it does work on Android. I must just have something wrong in my setup. When I initially tried including the shaders as described in the readme, I got the following error:

Shader compiler: internal error compiling shader snippet type=0 platform=5: Error polling external process 

Does that mean anything to you? Since it seemed to work fine in the editor without including the shaders I left them out but it seems that is a mistake. However when I compile the code with the shaders I get the above error in the Unity console and subsequently when I try and run the code it ends abruptly whenever I invoke a transition.

If you have any other thoughts I'd love to hear them. Best regards!

**Comment by prime31** [comment]
That's an odd one. It could be a Unity bug. I'd suggest shooting them a bug
report for that or trying TK in an empty project just to isolate it and see
if the issue persists there.

Mike

**Comment by davidandreoletti** [comment]
My application also displays pink screens when transitioning between scene on Android 4.4 and OSX 10.11.3 (built with Unity 5.2.4f1). The transition works perfectly when running in the Editor. Note: there is no error displayed in the console (unlike in @cluckeyetea 's case ). 

@cluckeyetea DId you find the root cause ?
@prime31 Do you think it is a Unity related bug ?

**Comment by prime31** [comment]
@davidandreoletti, did you follow the instructions in the README with regard to actually including the shaders in your build?
